# Generated by Django 5.0 on 2024-01-08 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='respond_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='respond_title',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
