# Generated by Django 5.0 on 2024-01-08 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_message_respond_text_message_respond_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='respond_text',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='respond_title',
            field=models.CharField(blank=True, default='', max_length=40, null=True),
        ),
    ]
